export const CLIENTNOTES = 'CLIENTNOTES';
export const CLIENTNOTES_SUCCESS = 'CLIENTNOTES_SUCCESS';
export const CLIENTNOTES_ERROR = 'CLIENTNOTES_ERROR';

export const CLIENTNOTES_GET = 'CLIENTNOTES_GET';
export const CLIENTNOTES_GET_SUCCESS = 'CLIENTNOTES_GET_SUCCESS';
export const CLIENTNOTES_GET_ERROR = 'CLIENTNOTES_GET_ERROR';

export const CLIENTNOTES_CREATE = 'CLIENTNOTES_CREATE';
export const CLIENTNOTES_CREATE_SUCCESS = 'CLIENTNOTES_CREATE_SUCCESS';
export const CLIENTNOTES_CREATE_ERROR = 'CLIENTNOTES_CREATE_ERROR';

export const CLIENTNOTES_UPDATE = 'CLIENTNOTES_UPDATE';
export const CLIENTNOTES_UPDATE_SUCCESS = 'CLIENTNOTES_UPDATE_SUCCESS';
export const CLIENTNOTES_UPDATE_ERROR = 'CLIENTNOTES_UPDATE_ERROR';

export const HEIGHTANDWEIGHT = 'HEIGHTANDWEIGHT';
export const HEIGHTANDWEIGHT_SUCCESS = 'HEIGHTANDWEIGHT_SUCCESS';
export const HEIGHTANDWEIGHT_ERROR = 'HEIGHTANDWEIGHT_ERROR';

export const HEIGHTANDWEIGHT_GET = 'HEIGHTANDWEIGHT_GET';
export const HEIGHTANDWEIGHT_GET_SUCCESS = 'HEIGHTANDWEIGHT_GET_SUCCESS';
export const HEIGHTANDWEIGHT_GET_ERROR = 'HEIGHTANDWEIGHT_GET_ERROR';

export const HEIGHTANDWEIGHT_CREATE = 'HEIGHTANDWEIGHT_CREATE';
export const HEIGHTANDWEIGHT_CREATE_SUCCESS = 'HEIGHTANDWEIGHT_CREATE_SUCCESS';
export const HEIGHTANDWEIGHT_CREATE_ERROR = 'HEIGHTANDWEIGHT_CREATE_ERROR';

export const HEIGHTANDWEIGHT_UPDATE = 'HEIGHTANDWEIGHT_UPDATE';
export const HEIGHTANDWEIGHT_UPDATE_SUCCESS = 'HEIGHTANDWEIGHT_UPDATE_SUCCESS';
export const HEIGHTANDWEIGHT_UPDATE_ERROR = 'HEIGHTANDWEIGHT_UPDATE_ERROR';

export const TRANSFEROFCARE = 'TRANSFEROFCARE';
export const TRANSFEROFCARE_SUCCESS = 'TRANSFEROFCARE_SUCCESS';
export const TRANSFEROFCARE_ERROR = 'TRANSFEROFCARE_ERROR';

export const TRANSFEROFCARE_GET = 'TRANSFEROFCARE_GET';
export const TRANSFEROFCARE_GET_SUCCESS = 'TRANSFEROFCARE_GET_SUCCESS';
export const TRANSFEROFCARE_GET_ERROR = 'TRANSFEROFCARE_GET_ERROR';

export const TRANSFEROFCARE_CREATE = 'TRANSFEROFCARE_CREATE';
export const TRANSFEROFCARE_CREATE_SUCCESS = 'TRANSFEROFCARE_CREATE_SUCCESS';
export const TRANSFEROFCARE_CREATE_ERROR = 'TRANSFEROFCARE_CREATE_ERROR';

export const CANCERMDT = 'CANCERMDT';
export const CANCERMDT_SUCCESS = 'CANCERMDT_SUCCESS';
export const CANCERMDT_ERROR = 'CANCERMDT_ERROR';

export const CANCERMDT_GET = 'CANCERMDT_GET';
export const CANCERMDT_GET_SUCCESS = 'CANCERMDT_GET_SUCCESS';
export const CANCERMDT_GET_ERROR = 'CANCERMDT_GET_ERROR';

export const CANCERMDT_CREATE = 'CANCERMDT_CREATE';
export const CANCERMDT_CREATE_SUCCESS = 'CANCERMDT_CREATE_SUCCESS';
export const CANCERMDT_CREATE_ERROR = 'CANCERMDT_CREATE_ERROR';

export const CANCERMDT_UPDATE = 'CANCERMDT_UPDATE';
export const CANCERMDT_UPDATE_SUCCESS = 'CANCERMDT_UPDATE_SUCCESS';
export const CANCERMDT_UPDATE_ERROR = 'CANCERMDT_UPDATE_ERROR';