sudo: required
dist: trusty

language: node_js
node_js:
  - "6"

install:
  - npm install

before_script:
  - npm install -g gulp

script: gulp build

notifications:
  email:
    on_failure: change
    on_success: change

branches:
  only:
    - master

env:
    global:
        - secure: "l/LvvnFfcibspfWu/WxOVGB53ZZUw/v0y4Zw9LgSVZ6khbgncoD7IDHTeuioYKI7YbR33AGzOIEs9mZownhRs8FdGPSZS8YKANjt9aD+K6+CMVG7Z4RESJoXQwsug3YPtAhEaPJlWOKpkNqs8dLaZjfF/RScts8CK/1+C80K9twLqm7pUUq6ysMLsigoyFjZbZs8uNxbmRO1j2hRNvu8uI2dMDha8gMtxnAlVLbZigAte2ofBuGfSS+t6rDLnYlP71q6Oac6vZUntaugpC+/XjnV7uOvwK2FyZ6NOBa+Cd93myQnDre9lg82QyrKwZYdADU2C8FZfMfGuPm/G1fGxjmixBdhP5ioZjcLyIzoG1/DC+JdyCtDDzFWIG52GoHzBwR7RGIOMyRXKHNJHrFxhhruvKBno3lsnFlBHVJuu8bOmg007bNdA7oJmMOFF7zzsEYq5CDz4faf2l7zVRPSwFOm01vrBcAt9gjEtqeE9qtbIRo+c/5oTDgV29G+yRDk3XFwwEY4iLb/r4uNYEHKW8ttPThvAXunziGVw6KkJCRCXf4D7FCx893c6kPfnpOf/dXI8Vn4HKNVdyY0hFPmZU9HgMOuxshjraq6dsdELwRtZewf+aswtbzDq1o7Hk6CgSqERtjbtI9CKhOCNsNj91+4r5Ji9qx1eFo3Mwnp+EU="
        - secure: "psHd5ykgqAHkPDeHacnfqPoKEDxWTug/kXN6sUed6jJnDEC3htI8iSzktV908RiA14Z6AgOdXbHPDNnH2SVENnUIgYE0T6FKbn5nNZKLKE4CC3FW9gDrea27iYAF6ZfyeZyKsUwPM8GM+qqviVxRHQerMHnU1iP+T+zpb1b3BPzXMomjxLbzUPLdFOHc/QymrIwx5PYUEzjZPvUHpL3oxdLQA7rs7SgW5Jx0TorXrgfteb/KlkfrKj7byU5OELj0GYiua+YL73VL9CGM9OKC7GPGWZiL9xXxODlQ5fObyun68Ef/fxlgnba0bEbZLrYW9g8J8d82GV4PVzI66eqUE1p/YSASk6qIDcjzrY2c0FEijXDsTQ7QzM7jyizTmL7gwZk0824Sxmy75s+n6I0r3c3CGxIeaxlAuOuFG0WgGMZ3ClV6o18zK//Eow7gBmbNjNGCnWngM8qU5U4cAwVkP2pSACqcwhWxSfmrSmo8bQw2up2BwEZvGpDN1Entb2vy9PeQqf+6CP3XH8PM08hSr+hLaIZ2G8qYnVl4pkIThuZku4BFiWpBIOLL+Bv2bjHsDB0BUiIbT7Xg19CwjjDminnSgf6TuUU1a3M9OfqD9dckJw86UgLR4Mo5GpqAGJG7/VUZddkeIKYT2jAQZictogcrbDqFd17wJUrGj8UxvdE="
        - secure: "iCMwSiUfmTVuxcvsD10T/0JXLbTTNLpK3z4S4BMCN7cEjOqE0NZ/iKRiK/1ncsH/GRYsx3C7OVokk6ElgEZ+nbCpK5V1njaxkqBdqTvxNGSOLfJdgB2OV6JR3Jqi434aiyF4MCKbHajGY/TkcUVIF9APzv8hfmb4r1NW1B+RugirdtwU0aYMYv0h0DY9AZvscL1VoamXwiYoFW+A7SIySnCrLK9l6ljqS9RClGpu3h8pDeh+KVcqyHHJOLPSV4r1WfmHImLn7rSSSPvxhYZfiMQqWz3hMSM5wCjcHrTQbBmBZAZULWkZtkZgoD7OMnrgACDFGkyzA9w3Mlnm+UgmlASEzuc84gYpRkYf9PfiyJtb4+4WRuUo3cOmrW2MJ397vYbhLQ+jjaGKONJHajWAt2OJekfoW4SWJNmvqyUYNIEpPukRBnisp8Zwr8X46y1oBd9HunzdkVyqj3VtSBvwHAF1g7igM3Mij01gE3pOw100tcODRO5rushJsJ5bkS4mRKxjdZByszJ/DrywxY4w2lVa0FmF2QwzK3d2o1bqzHMwpET1X7SWzkxPivglullfFq2uW+YO7Bc5wn/8pdK4vOW/pTwx0QGG7ROrVQkvg8CfKaEJv2416ougE+vxuHaGmaIjENsifPhl1QSlj4NgBk8RCXKmWMobmS0NwlW86tY="
        - secure: "Z/2DAOdvG0/JgAUy7nKFvoOprn7u/hGBuZ2ri4WnCAzyTSc1dWdng+FeK/VPGGzR4uam+0shFXEtAqZmxK9j3wLS2e45ZMErbx2vftu/W6CJMRjNe7qs3m+mcueHDjnNTfhBq7IzuM3X88c+W6y/j7gR8o1S9NMllxnnFAe5xqoS2luFvnel1V2ajwvnbsSppQB4xuJm+fCLKDoD21Ah/C5Ch9NYYxpTEel+u4e07Y6tUNovGbQuqcKv3XcD6n9+xdwxqMB1QMpF+8OdVHLrVjbgqLBU9k9YHojegW4pCCn/peKsuawIZIv9xoNK95v3dq00KboJhA7JEfwPiBNFsTuFjWAFKJOUMIeGmyHt5MkJDMMFxL2qmOhee8CQkte3lgEoChJggKHdDvsWtpKyHeohymwF3kpv6JmmGKiv/0teqWZLftz6Z3MLuV52JA4d1iuy+VUDLagEtWSlq1tL8PmQ8paiEwyC6Ii/lFfBty8o5X3cffgpRlE12/ZvupManYYnlI3Ub9AvrICrYoR4ja0Ur2HWMwzBQqptTY5jjcnarPkA3C30qBZ0n+3v215q44GxfSCgu4NgMm0vr5x4h+VjL4Jrb4IOZLoAylT9cxxwOYvMU+Vp3c+JcUnGIrmsr+ktXkq/QXr2v8Fuu3XM5UvLZAk1MzpPNHcDfVfjqxU="

addons:
    apt:
        packages:
            - sshpass

after_success:
    "curl --ftp-create-dirs -T uploadfilename -u $DEPLOY_USER:$DEPLOY_PASS ftp://$DEPLOY_HOST/home/chibi/www"