sudo: required
dist: trusty

language: node_js
node_js:
  - "6"

install:
  - npm install

before_script:
  - npm install -g gulp

script: gulp build

notifications:
  email:
    on_failure: change
    on_success: change

branches:
  only:
    - master

env:
  global:
    - "FTP_USER=chibi"
    - "FTP_PASSWORD=changeme"
after_success:
    "curl uploadfilename -u $FTP_USER:$FTP_PASSWORD ftp://193.107.128.193/home/chibi/www"